[package]
name = "arithmetipy"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "arithmetipy"
crate-type = ["cdylib"]

[dependencies]
arithmetify = "0.1"
pyo3 = "0.26.0"
